name: Sphinx Build

on:
  push:
    branches:
      - main

jobs:
  sphinx-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installs
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget python3 python3-pip python3-venv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python depencencies
        run: pip3 install -r requirements.txt

      - name: Build docs
        run: make docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: html
          retention-days: 90

  deploy:
    needs: sphinx-build

    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 

